<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJj1utPS\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJj1utPS/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerJj1utPS.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerJj1utPS\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerJj1utPS\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Jj1utPS',
    'container.build_id' => 'ff66e712',
    'container.build_time' => 1543323221,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJj1utPS');
