<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBBvdk25\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBBvdk25/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBBvdk25.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBBvdk25\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerBBvdk25\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'BBvdk25',
    'container.build_id' => 'ab3cd7c1',
    'container.build_time' => 1542815361,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerBBvdk25');
